export enum Role {
    ADMIN = 'ADMIN',
    GESTOR = 'GESTOR',
    INSTRUCTOR = 'INSTRUCTOR',
    EMPLEADO = 'EMPLEADO'
}

export enum Action {
    CREATE_USER = 'CREATE_USER',
    EDIT_USER = 'EDIT_USER',
    DELETE_USER = 'DELETE_USER',
    UPLOAD_DOCUMENT = 'UPLOAD_DOCUMENT',
    DELETE_DOCUMENT = 'DELETE_DOCUMENT',
    SEND_PROMPT = 'SEND_PROMPT',
    UPDATE_PROFILE_PHOTO = 'UPDATE_PROFILE_PHOTO',
    VIEW_CONVERSATION_HISTORY = 'VIEW_CONVERSATION_HISTORY'
}
