export const PERMISSIONS = {
    CREATE_USER: ['ADMIN', 'GESTOR'],
    UPLOAD_DOCUMENT: ['ADMIN', 'INSTRUCTOR'],
    LIST_DOCUMENTS: ['ADMIN', 'INSTRUCTOR', 'GESTOR'],
    DELETE_DOCUMENT: ['ADMIN', 'INSTRUCTOR'],
    DOWNLOAD_DOCUMENT: ['ADMIN', 'INSTRUCTOR', 'GESTOR'],
    CHAT_ACCESS: ['ADMIN', 'GESTOR', 'INSTRUCTOR', 'EMPLEADO']
};
